name: craigpark.consulting
favicon: null
layout_spectrum: 0.30708640441298485
typography_spectrum: 0.3482658623252064
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.6824050392024219
  lightness: 0.657433470711112
  saturation: 0.3159537941683084
  rhythmicContrast: 0.5099968428257853
purpose: []
